### ISSUE TITLE
Does it include the week of the quarter?

### ISSUE THREAD

**Issue by ThibaultBagot** [sql-bi/DaxDateTemplate#31]
It'd be interesting to look at the week of the quarter typically from 1 to 13 instead of the 53 annual weeks. What do yo uthink?
Is it already in there?

**Comment by marcosqlbi** [comment]
You can just create a column using MOD ( 'Date'[FW WeekNumber] - 1, 13 ) + 1, which works well for 52 weeks (ISO Calendar). Because there are no standards about managing the 53 weeks, you should figure out a business logic that can be good for your requirements. It's hard to create a generic solution for that.
