### ISSUE TITLE
VAR FirstDayOfWeek

### ISSUE THREAD

**Issue by ronkochanowski** [sql-bi/DaxDateTemplate#42]
VAR FirstDayOfWeek is set to 1, for Monday as the first day of the week.  Yet, the measure 'Fiscal DatePreviousWeek' has the last day as Monday of the current week.  Why would it not display Sunday?  I'm not following the logic.

**Comment by ronkochanowski** [comment]
Copied the Date formula into a different pbi file and am not having the issues there.

**Comment by marcosqlbi** [comment]
That column has this definition: "Same relative day in previous fiscal week"
https://www.sqlbi.com/articles/reference-date-table-in-dax-and-power-bi/

Did you expect a different behavior?

**Comment by ronkochanowski** [comment]
I was looking for something different, and was attempting to use this measure to come up it it. Today is Friday, August 28. The same period a week ago would be Friday, August 21, correct?  I dropped the measure ‘Fiscal DatePreviousWeek’ into a grid. Changed the filter ‘First Value of’ To ‘Last Value of’ and the date that displayed was August 24, this past Monday. It seemed to me that the last value of the previous week would be Sunday, since I have the VAR FirstDayOfWeek set to 1 in the configuration.

**Comment by marcosqlbi** [comment]
"Fiscal DatePreviousWeek" is a column, you dropped a "measure" with the same name. I assume you are referencing the column, otherwise please clarify.
I just double-checked and the value of "Fiscal DatePreviousWeek" for Aug 28 is Aug21, as expected. But I don't understand what you mean with "Changed the filter ‘First Value of’ To ‘Last Value of’ " - can you clarify exactly how you are creating the report? Can you share the DAX query captured with Performance Analyzer?

**Comment by ronkochanowski** [comment]
Thank you Marco, In the process of standardizing our Date tables, this
particular report got messed up. One of the measures that we'd defined was
not producing correct results, but is now corrected. My apologies for any
hardship.

**Comment by marcosqlbi** [comment]
No problems - thanks for closing the loop, I can close the issue now! 👍
